; ; PlatformIO Project Configuration File
; ;
; ;   Build options: build flags, source filter
; ;   Upload options: custom upload port, speed and extra flags
; ;   Library options: dependencies, extra library storages
; ;   Advanced options: extra scripting
; ;
; ; Please visit documentation for the other options and examples
; ; https://docs.platformio.org/page/projectconf.html

; [env:freenove_esp32_s3_wroom]
; platform = espressif32
; board = freenove_esp32_s3_wroom
; framework = arduino
; monitor_speed = 115200
; monitor_raw = true
; build_unflags = -std=gnu++11
; build_flags = 
;     -std=gnu++17
;     -Wl,-u_printf_float
;     -DENABLE_DEBUG
; lib_deps =
;     littlemanbuilds/ESP32_MCPWM@^1.1.1
;     blynkkk/Blynk@^1.3.2
; platform_packages =
;    framework-arduinoespressif32@https://github.com/maxgerhardt/pio-framework-bluepad32/archive/refs/heads/main.zip











; ; PlatformIO Project Configuration File

; [env:freenove_esp32_s3_wroom]
; platform = espressif32
; board = freenove_esp32_s3_wroom
; framework = arduino
; monitor_speed = 115200
; monitor_raw = true
; build_unflags = -std=gnu++11
; build_flags =
;     -std=gnu++17
;     -Wl,-u_printf_float
;     -DENABLE_DEBUG
; lib_deps =
;     littlemanbuilds/ESP32_MCPWM@^1.1.1



[env:freenove_esp32_s3_wroom]
platform = espressif32
board = freenove_esp32_s3_wroom
framework = arduino
monitor_speed = 115200
monitor_raw = true
build_unflags = -std=gnu++11
build_flags =
    -std=gnu++17
    -Wl,-u_printf_float
    -DENABLE_DEBUG
lib_deps =
    littlemanbuilds/ESP32_MCPWM@^1.1.1